"""create timeframe specific ohlcv tables

Revision ID: ee23c3b5d5df
Revises: 000000000001
Create Date: 2025-09-11 14:41:30.949246

"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "ee23c3b5d5df"
down_revision = "000000000001"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "raw_ohlcv_15m",
        sa.Column("timestamp", sa.BigInteger(), nullable=False),
        sa.Column("token", sa.String(), nullable=False),
        sa.Column("open", sa.Float(precision=53), nullable=False),
        sa.Column("high", sa.Float(precision=53), nullable=False),
        sa.Column("low", sa.Float(precision=53), nullable=False),
        sa.Column("close", sa.Float(precision=53), nullable=False),
        sa.Column("volume", sa.Float(precision=53), nullable=False),
        sa.PrimaryKeyConstraint("timestamp", "token"),
        sa.UniqueConstraint("timestamp", "token", name="_timestamp_token_uc_15m"),
    )
    op.create_table(
        "raw_ohlcv_1d",
        sa.Column("timestamp", sa.BigInteger(), nullable=False),
        sa.Column("token", sa.String(), nullable=False),
        sa.Column("open", sa.Float(precision=53), nullable=False),
        sa.Column("high", sa.Float(precision=53), nullable=False),
        sa.Column("low", sa.Float(precision=53), nullable=False),
        sa.Column("close", sa.Float(precision=53), nullable=False),
        sa.Column("volume", sa.Float(precision=53), nullable=False),
        sa.PrimaryKeyConstraint("timestamp", "token"),
        sa.UniqueConstraint("timestamp", "token", name="_timestamp_token_uc_1d"),
    )
    op.create_table(
        "raw_ohlcv_1h",
        sa.Column("timestamp", sa.BigInteger(), nullable=False),
        sa.Column("token", sa.String(), nullable=False),
        sa.Column("open", sa.Float(precision=53), nullable=False),
        sa.Column("high", sa.Float(precision=53), nullable=False),
        sa.Column("low", sa.Float(precision=53), nullable=False),
        sa.Column("close", sa.Float(precision=53), nullable=False),
        sa.Column("volume", sa.Float(precision=53), nullable=False),
        sa.PrimaryKeyConstraint("timestamp", "token"),
        sa.UniqueConstraint("timestamp", "token", name="_timestamp_token_uc_1h"),
    )
    op.create_table(
        "raw_ohlcv_4h",
        sa.Column("timestamp", sa.BigInteger(), nullable=False),
        sa.Column("token", sa.String(), nullable=False),
        sa.Column("open", sa.Float(precision=53), nullable=False),
        sa.Column("high", sa.Float(precision=53), nullable=False),
        sa.Column("low", sa.Float(precision=53), nullable=False),
        sa.Column("close", sa.Float(precision=53), nullable=False),
        sa.Column("volume", sa.Float(precision=53), nullable=False),
        sa.PrimaryKeyConstraint("timestamp", "token"),
        sa.UniqueConstraint("timestamp", "token", name="_timestamp_token_uc_4h"),
    )
    op.drop_index(op.f("ix_raw_ohlcv_timestamp"), table_name="raw_ohlcv")
    op.drop_index(op.f("ix_raw_ohlcv_token"), table_name="raw_ohlcv")
    op.drop_table("raw_ohlcv")
    op.drop_column("feature_store_1h", "pressure_correlation_5bp_100bp_4h")
    op.drop_column("feature_store_1h", "vanna_exposure")
    op.drop_column("feature_store_1h", "liquidity_percentile_rank_4h")
    op.drop_column("feature_store_1h", "imbalance_gradient_100bp_to_500bp")
    op.drop_column("feature_store_1h", "buy_sell_trade_ratio")
    op.drop_column("feature_store_1h", "market_maker_inventory_proxy_15m")
    op.drop_column("feature_store_1h", "effective_depth_25bp_zscore_24h")
    op.drop_column("feature_store_1h", "order_count_concentration_5bp")
    op.drop_column("feature_store_1h", "net_gamma_exposure_zscore_24h")
    op.drop_column("feature_store_1h", "avg_trade_size_usd_zscore_24h")
    op.drop_column("feature_store_1h", "long_short_ratio_zscore")
    op.drop_column("feature_store_1h", "eth_dvol_1d")
    op.drop_column("feature_store_1h", "net_delta_exposure")
    op.drop_column("feature_store_1h", "cluster_strength_largest_below_pct")
    op.drop_column("feature_store_1h", "cluster_strength_nearest_below_pct")
    op.drop_column("feature_store_1h", "btc_dvol_1d")
    op.drop_column("feature_store_1h", "long_short_ratio_extreme_evt")
    op.drop_column("feature_store_1h", "pressure_inversion_strength")
    op.drop_column("feature_store_1h", "net_buy_momentum_15min")
    op.drop_column("feature_store_1h", "pressure_momentum_5bp_15min")
    op.drop_column("feature_store_1h", "imbalance_gradient_25bp_to_100bp")
    op.drop_column("feature_store_1h", "iv_shock_evt")
    op.drop_column("feature_store_1h", "volatility_surface_skew_15m")
    op.drop_column("feature_store_1h", "market_depth_imbalance_momentum_15m")
    op.drop_column("feature_store_1h", "pressure_mean_reversion_5bp_4h")
    op.drop_column("feature_store_1h", "depth_momentum_5bp_15min")
    op.drop_column("feature_store_1h", "charm_exposure_zscore_24h")
    op.drop_column("feature_store_1h", "pressure_momentum_25bp_15min")
    op.drop_column("feature_store_1h", "effective_depth_100bp")
    op.drop_column("feature_store_1h", "pressure_correlation_25bp_500bp_4h")
    op.drop_column("feature_store_1h", "cluster_strength_largest_above_pct")
    op.drop_column("feature_store_1h", "spread_percentile_rank_4h")
    op.drop_column("feature_store_1h", "price_volatility_4h")
    op.drop_column("feature_store_1h", "iv_trend_strength")
    op.drop_column("feature_store_1h", "btc_iv_zscore_30d")
    op.drop_column("feature_store_1h", "net_buy_pressure_ratio")
    op.drop_column("feature_store_1h", "options_flow_sentiment_15m")
    op.drop_column("feature_store_1h", "order_book_resilience_15m")
    op.drop_column("feature_store_1h", "order_flow_toxicity_15m")
    op.drop_column("feature_store_1h", "pressure_concentration_near")
    op.drop_column("feature_store_1h", "gamma_exposure_zscore_24h")
    op.drop_column("feature_store_1h", "effective_depth_5bp_zscore_24h")
    op.drop_column("feature_store_1h", "pressure_inversion_5bp_vs_500bp")
    op.drop_column("feature_store_1h", "net_delta_exposure_zscore_24h")
    op.drop_column("feature_store_1h", "volatility_risk_premium_15m")
    op.drop_column("feature_store_1h", "volume_volatility_4h")
    op.drop_column("feature_store_1h", "trade_frequency_momentum_60min")
    op.drop_column("feature_store_1h", "pressure_gradient_divergence")
    op.drop_column("feature_store_1h", "iv_zscore_24h")
    op.drop_column("feature_store_1h", "liquidity_concentration_25bp_vs_500bp")
    op.drop_column("feature_store_1h", "imbalance_consistency_score")
    op.drop_column("feature_store_1h", "avg_order_size_100bp_zscore_24h")
    op.drop_column("feature_store_1h", "market_microstructure_toxicity_15m")
    op.drop_column("feature_store_1h", "gamma_squeeze_potential_15m")
    op.drop_column("feature_store_1h", "iv_slope")
    op.drop_column("feature_store_1h", "depth_imbalance_5bp")
    op.drop_column("feature_store_1h", "iv_slope_4h")
    op.drop_column("feature_store_1h", "depth_pressure_correlation_5bp_4h")
    op.drop_column("feature_store_1h", "pressure_gradient_far")
    op.drop_column("feature_store_1h", "liquidity_adjusted_momentum_15m")
    op.drop_column("feature_store_1h", "distance_to_largest_cluster_below_pct")
    op.drop_column("feature_store_1h", "net_gamma_density")
    op.drop_column("feature_store_1h", "liquidity_stress_indicator_15m")
    op.drop_column("feature_store_1h", "imbalance_momentum_5bp_15min")
    op.drop_column("feature_store_1h", "net_buy_pressure_absolute_zscore_24h")
    op.drop_column("feature_store_1h", "liquidity_concentration_5bp_vs_100bp")
    op.drop_column("feature_store_1h", "imbalance_gradient_5bp_to_25bp")
    op.drop_column("feature_store_1h", "avg_order_size_5bp_zscore_24h")
    op.drop_column("feature_store_1h", "options_orderbook_imbalance")
    op.drop_column("feature_store_1h", "eth_put_call_ratio_1h_zscore_30d")
    op.drop_column("feature_store_1h", "vanna_exposure_zscore_24h")
    op.drop_column("feature_store_1h", "trade_frequency")
    op.drop_column("feature_store_1h", "depth_imbalance_25bp")
    op.drop_column("feature_store_1h", "pressure_gradient_near")
    op.drop_column("feature_store_1h", "depth_imbalance_500bp")
    op.drop_column("feature_store_1h", "realized_volatility_60min")
    op.drop_column("feature_store_1h", "distance_to_largest_cluster_above_pct")
    op.drop_column("feature_store_1h", "cluster_strength_nearest_above_pct")
    op.drop_column("feature_store_1h", "eth_iv_zscore_30d")
    op.drop_column("feature_store_1h", "distance_to_nearest_cluster_below_pct")
    op.drop_column("feature_store_1h", "depth_momentum_25bp_60min")
    op.drop_column("feature_store_1h", "delta_gamm_inter")
    op.drop_column("feature_store_1h", "imbalance_momentum_25bp_60min")
    op.drop_column("feature_store_1h", "options_gamma_hedging_flow_15m")
    op.drop_column("feature_store_1h", "depth_imbalance_100bp")
    op.drop_column("feature_store_1h", "pressure_momentum_5bp_60min")
    op.drop_column("feature_store_1h", "buy_volume_dominance")
    op.drop_column("feature_store_1h", "liquidity_provision_cost_15m")
    op.drop_column("feature_store_1h", "long_short_ratio_slope")
    op.drop_column("feature_store_1h", "distance_to_nearest_cluster_above_pct")
    op.drop_column("feature_store_1h", "iv_pctile_30d")
    op.drop_column("feature_store_1h", "pressure_gradient_medium")
    op.drop_column("feature_store_1h", "put_call_ratio_1h")
    op.drop_column("feature_store_1h", "btc_put_call_ratio_zscore_30d")
    op.drop_column("feature_store_1h", "spread_volatility_4h")
    op.drop_column("feature_store_1h", "entropy_based_uncertainty_15m")
    op.drop_column("feature_store_4h", "pressure_correlation_5bp_100bp_4h")
    op.drop_column("feature_store_4h", "vanna_exposure")
    op.drop_column("feature_store_4h", "liquidity_percentile_rank_4h")
    op.drop_column("feature_store_4h", "imbalance_gradient_100bp_to_500bp")
    op.drop_column("feature_store_4h", "buy_sell_trade_ratio")
    op.drop_column("feature_store_4h", "market_maker_inventory_proxy_15m")
    op.drop_column("feature_store_4h", "effective_depth_25bp_zscore_24h")
    op.drop_column("feature_store_4h", "order_count_concentration_5bp")
    op.drop_column("feature_store_4h", "net_gamma_exposure_zscore_24h")
    op.drop_column("feature_store_4h", "avg_trade_size_usd_zscore_24h")
    op.drop_column("feature_store_4h", "long_short_ratio_zscore")
    op.drop_column("feature_store_4h", "eth_dvol_1d")
    op.drop_column("feature_store_4h", "net_delta_exposure")
    op.drop_column("feature_store_4h", "cluster_strength_largest_below_pct")
    op.drop_column("feature_store_4h", "cluster_strength_nearest_below_pct")
    op.drop_column("feature_store_4h", "btc_dvol_1d")
    op.drop_column("feature_store_4h", "long_short_ratio_extreme_evt")
    op.drop_column("feature_store_4h", "pressure_inversion_strength")
    op.drop_column("feature_store_4h", "net_buy_momentum_15min")
    op.drop_column("feature_store_4h", "pressure_momentum_5bp_15min")
    op.drop_column("feature_store_4h", "imbalance_gradient_25bp_to_100bp")
    op.drop_column("feature_store_4h", "iv_shock_evt")
    op.drop_column("feature_store_4h", "volatility_surface_skew_15m")
    op.drop_column("feature_store_4h", "market_depth_imbalance_momentum_15m")
    op.drop_column("feature_store_4h", "pressure_mean_reversion_5bp_4h")
    op.drop_column("feature_store_4h", "depth_momentum_5bp_15min")
    op.drop_column("feature_store_4h", "charm_exposure_zscore_24h")
    op.drop_column("feature_store_4h", "pressure_momentum_25bp_15min")
    op.drop_column("feature_store_4h", "effective_depth_100bp")
    op.drop_column("feature_store_4h", "pressure_correlation_25bp_500bp_4h")
    op.drop_column("feature_store_4h", "cluster_strength_largest_above_pct")
    op.drop_column("feature_store_4h", "spread_percentile_rank_4h")
    op.drop_column("feature_store_4h", "price_volatility_4h")
    op.drop_column("feature_store_4h", "iv_trend_strength")
    op.drop_column("feature_store_4h", "btc_iv_zscore_30d")
    op.drop_column("feature_store_4h", "net_buy_pressure_ratio")
    op.drop_column("feature_store_4h", "options_flow_sentiment_15m")
    op.drop_column("feature_store_4h", "order_book_resilience_15m")
    op.drop_column("feature_store_4h", "order_flow_toxicity_15m")
    op.drop_column("feature_store_4h", "pressure_concentration_near")
    op.drop_column("feature_store_4h", "gamma_exposure_zscore_24h")
    op.drop_column("feature_store_4h", "effective_depth_5bp_zscore_24h")
    op.drop_column("feature_store_4h", "pressure_inversion_5bp_vs_500bp")
    op.drop_column("feature_store_4h", "net_delta_exposure_zscore_24h")
    op.drop_column("feature_store_4h", "volatility_risk_premium_15m")
    op.drop_column("feature_store_4h", "volume_volatility_4h")
    op.drop_column("feature_store_4h", "trade_frequency_momentum_60min")
    op.drop_column("feature_store_4h", "pressure_gradient_divergence")
    op.drop_column("feature_store_4h", "iv_zscore_24h")
    op.drop_column("feature_store_4h", "liquidity_concentration_25bp_vs_500bp")
    op.drop_column("feature_store_4h", "imbalance_consistency_score")
    op.drop_column("feature_store_4h", "avg_order_size_100bp_zscore_24h")
    op.drop_column("feature_store_4h", "market_microstructure_toxicity_15m")
    op.drop_column("feature_store_4h", "gamma_squeeze_potential_15m")
    op.drop_column("feature_store_4h", "iv_slope")
    op.drop_column("feature_store_4h", "depth_imbalance_5bp")
    op.drop_column("feature_store_4h", "iv_slope_4h")
    op.drop_column("feature_store_4h", "depth_pressure_correlation_5bp_4h")
    op.drop_column("feature_store_4h", "pressure_gradient_far")
    op.drop_column("feature_store_4h", "liquidity_adjusted_momentum_15m")
    op.drop_column("feature_store_4h", "distance_to_largest_cluster_below_pct")
    op.drop_column("feature_store_4h", "net_gamma_density")
    op.drop_column("feature_store_4h", "liquidity_stress_indicator_15m")
    op.drop_column("feature_store_4h", "imbalance_momentum_5bp_15min")
    op.drop_column("feature_store_4h", "net_buy_pressure_absolute_zscore_24h")
    op.drop_column("feature_store_4h", "liquidity_concentration_5bp_vs_100bp")
    op.drop_column("feature_store_4h", "imbalance_gradient_5bp_to_25bp")
    op.drop_column("feature_store_4h", "avg_order_size_5bp_zscore_24h")
    op.drop_column("feature_store_4h", "options_orderbook_imbalance")
    op.drop_column("feature_store_4h", "eth_put_call_ratio_1h_zscore_30d")
    op.drop_column("feature_store_4h", "vanna_exposure_zscore_24h")
    op.drop_column("feature_store_4h", "trade_frequency")
    op.drop_column("feature_store_4h", "depth_imbalance_25bp")
    op.drop_column("feature_store_4h", "pressure_gradient_near")
    op.drop_column("feature_store_4h", "depth_imbalance_500bp")
    op.drop_column("feature_store_4h", "realized_volatility_60min")
    op.drop_column("feature_store_4h", "distance_to_largest_cluster_above_pct")
    op.drop_column("feature_store_4h", "cluster_strength_nearest_above_pct")
    op.drop_column("feature_store_4h", "eth_iv_zscore_30d")
    op.drop_column("feature_store_4h", "distance_to_nearest_cluster_below_pct")
    op.drop_column("feature_store_4h", "depth_momentum_25bp_60min")
    op.drop_column("feature_store_4h", "delta_gamm_inter")
    op.drop_column("feature_store_4h", "imbalance_momentum_25bp_60min")
    op.drop_column("feature_store_4h", "options_gamma_hedging_flow_15m")
    op.drop_column("feature_store_4h", "depth_imbalance_100bp")
    op.drop_column("feature_store_4h", "pressure_momentum_5bp_60min")
    op.drop_column("feature_store_4h", "buy_volume_dominance")
    op.drop_column("feature_store_4h", "liquidity_provision_cost_15m")
    op.drop_column("feature_store_4h", "long_short_ratio_slope")
    op.drop_column("feature_store_4h", "distance_to_nearest_cluster_above_pct")
    op.drop_column("feature_store_4h", "iv_pctile_30d")
    op.drop_column("feature_store_4h", "pressure_gradient_medium")
    op.drop_column("feature_store_4h", "put_call_ratio_1h")
    op.drop_column("feature_store_4h", "btc_put_call_ratio_zscore_30d")
    op.drop_column("feature_store_4h", "spread_volatility_4h")
    op.drop_column("feature_store_4h", "entropy_based_uncertainty_15m")
    op.drop_column("feature_store_8h", "pressure_correlation_5bp_100bp_4h")
    op.drop_column("feature_store_8h", "vanna_exposure")
    op.drop_column("feature_store_8h", "liquidity_percentile_rank_4h")
    op.drop_column("feature_store_8h", "imbalance_gradient_100bp_to_500bp")
    op.drop_column("feature_store_8h", "buy_sell_trade_ratio")
    op.drop_column("feature_store_8h", "market_maker_inventory_proxy_15m")
    op.drop_column("feature_store_8h", "effective_depth_25bp_zscore_24h")
    op.drop_column("feature_store_8h", "order_count_concentration_5bp")
    op.drop_column("feature_store_8h", "net_gamma_exposure_zscore_24h")
    op.drop_column("feature_store_8h", "avg_trade_size_usd_zscore_24h")
    op.drop_column("feature_store_8h", "long_short_ratio_zscore")
    op.drop_column("feature_store_8h", "eth_dvol_1d")
    op.drop_column("feature_store_8h", "net_delta_exposure")
    op.drop_column("feature_store_8h", "cluster_strength_largest_below_pct")
    op.drop_column("feature_store_8h", "cluster_strength_nearest_below_pct")
    op.drop_column("feature_store_8h", "btc_dvol_1d")
    op.drop_column("feature_store_8h", "long_short_ratio_extreme_evt")
    op.drop_column("feature_store_8h", "pressure_inversion_strength")
    op.drop_column("feature_store_8h", "net_buy_momentum_15min")
    op.drop_column("feature_store_8h", "pressure_momentum_5bp_15min")
    op.drop_column("feature_store_8h", "imbalance_gradient_25bp_to_100bp")
    op.drop_column("feature_store_8h", "iv_shock_evt")
    op.drop_column("feature_store_8h", "volatility_surface_skew_15m")
    op.drop_column("feature_store_8h", "market_depth_imbalance_momentum_15m")
    op.drop_column("feature_store_8h", "pressure_mean_reversion_5bp_4h")
    op.drop_column("feature_store_8h", "depth_momentum_5bp_15min")
    op.drop_column("feature_store_8h", "charm_exposure_zscore_24h")
    op.drop_column("feature_store_8h", "pressure_momentum_25bp_15min")
    op.drop_column("feature_store_8h", "effective_depth_100bp")
    op.drop_column("feature_store_8h", "pressure_correlation_25bp_500bp_4h")
    op.drop_column("feature_store_8h", "cluster_strength_largest_above_pct")
    op.drop_column("feature_store_8h", "spread_percentile_rank_4h")
    op.drop_column("feature_store_8h", "price_volatility_4h")
    op.drop_column("feature_store_8h", "iv_trend_strength")
    op.drop_column("feature_store_8h", "btc_iv_zscore_30d")
    op.drop_column("feature_store_8h", "net_buy_pressure_ratio")
    op.drop_column("feature_store_8h", "options_flow_sentiment_15m")
    op.drop_column("feature_store_8h", "order_book_resilience_15m")
    op.drop_column("feature_store_8h", "order_flow_toxicity_15m")
    op.drop_column("feature_store_8h", "pressure_concentration_near")
    op.drop_column("feature_store_8h", "gamma_exposure_zscore_24h")
    op.drop_column("feature_store_8h", "effective_depth_5bp_zscore_24h")
    op.drop_column("feature_store_8h", "pressure_inversion_5bp_vs_500bp")
    op.drop_column("feature_store_8h", "net_delta_exposure_zscore_24h")
    op.drop_column("feature_store_8h", "volatility_risk_premium_15m")
    op.drop_column("feature_store_8h", "volume_volatility_4h")
    op.drop_column("feature_store_8h", "trade_frequency_momentum_60min")
    op.drop_column("feature_store_8h", "pressure_gradient_divergence")
    op.drop_column("feature_store_8h", "iv_zscore_24h")
    op.drop_column("feature_store_8h", "liquidity_concentration_25bp_vs_500bp")
    op.drop_column("feature_store_8h", "imbalance_consistency_score")
    op.drop_column("feature_store_8h", "avg_order_size_100bp_zscore_24h")
    op.drop_column("feature_store_8h", "market_microstructure_toxicity_15m")
    op.drop_column("feature_store_8h", "gamma_squeeze_potential_15m")
    op.drop_column("feature_store_8h", "iv_slope")
    op.drop_column("feature_store_8h", "depth_imbalance_5bp")
    op.drop_column("feature_store_8h", "iv_slope_4h")
    op.drop_column("feature_store_8h", "depth_pressure_correlation_5bp_4h")
    op.drop_column("feature_store_8h", "pressure_gradient_far")
    op.drop_column("feature_store_8h", "liquidity_adjusted_momentum_15m")
    op.drop_column("feature_store_8h", "distance_to_largest_cluster_below_pct")
    op.drop_column("feature_store_8h", "net_gamma_density")
    op.drop_column("feature_store_8h", "liquidity_stress_indicator_15m")
    op.drop_column("feature_store_8h", "imbalance_momentum_5bp_15min")
    op.drop_column("feature_store_8h", "net_buy_pressure_absolute_zscore_24h")
    op.drop_column("feature_store_8h", "liquidity_concentration_5bp_vs_100bp")
    op.drop_column("feature_store_8h", "imbalance_gradient_5bp_to_25bp")
    op.drop_column("feature_store_8h", "avg_order_size_5bp_zscore_24h")
    op.drop_column("feature_store_8h", "options_orderbook_imbalance")
    op.drop_column("feature_store_8h", "eth_put_call_ratio_1h_zscore_30d")
    op.drop_column("feature_store_8h", "vanna_exposure_zscore_24h")
    op.drop_column("feature_store_8h", "trade_frequency")
    op.drop_column("feature_store_8h", "depth_imbalance_25bp")
    op.drop_column("feature_store_8h", "pressure_gradient_near")
    op.drop_column("feature_store_8h", "depth_imbalance_500bp")
    op.drop_column("feature_store_8h", "realized_volatility_60min")
    op.drop_column("feature_store_8h", "distance_to_largest_cluster_above_pct")
    op.drop_column("feature_store_8h", "cluster_strength_nearest_above_pct")
    op.drop_column("feature_store_8h", "eth_iv_zscore_30d")
    op.drop_column("feature_store_8h", "distance_to_nearest_cluster_below_pct")
    op.drop_column("feature_store_8h", "depth_momentum_25bp_60min")
    op.drop_column("feature_store_8h", "delta_gamm_inter")
    op.drop_column("feature_store_8h", "imbalance_momentum_25bp_60min")
    op.drop_column("feature_store_8h", "options_gamma_hedging_flow_15m")
    op.drop_column("feature_store_8h", "depth_imbalance_100bp")
    op.drop_column("feature_store_8h", "pressure_momentum_5bp_60min")
    op.drop_column("feature_store_8h", "buy_volume_dominance")
    op.drop_column("feature_store_8h", "liquidity_provision_cost_15m")
    op.drop_column("feature_store_8h", "long_short_ratio_slope")
    op.drop_column("feature_store_8h", "distance_to_nearest_cluster_above_pct")
    op.drop_column("feature_store_8h", "iv_pctile_30d")
    op.drop_column("feature_store_8h", "pressure_gradient_medium")
    op.drop_column("feature_store_8h", "put_call_ratio_1h")
    op.drop_column("feature_store_8h", "btc_put_call_ratio_zscore_30d")
    op.drop_column("feature_store_8h", "spread_volatility_4h")
    op.drop_column("feature_store_8h", "entropy_based_uncertainty_15m")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "feature_store_8h",
        sa.Column(
            "entropy_based_uncertainty_15m",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_8h",
        sa.Column(
            "spread_volatility_4h",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_8h",
        sa.Column(
            "btc_put_call_ratio_zscore_30d",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_8h",
        sa.Column(
            "put_call_ratio_1h",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_8h",
        sa.Column(
            "pressure_gradient_medium",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_8h",
        sa.Column(
            "iv_pctile_30d",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_8h",
        sa.Column(
            "distance_to_nearest_cluster_above_pct",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_8h",
        sa.Column(
            "long_short_ratio_slope",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_8h",
        sa.Column(
            "liquidity_provision_cost_15m",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_8h",
        sa.Column(
            "buy_volume_dominance",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_8h",
        sa.Column(
            "pressure_momentum_5bp_60min",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_8h",
        sa.Column(
            "depth_imbalance_100bp",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_8h",
        sa.Column(
            "options_gamma_hedging_flow_15m",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_8h",
        sa.Column(
            "imbalance_momentum_25bp_60min",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_8h",
        sa.Column(
            "delta_gamm_inter",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_8h",
        sa.Column(
            "depth_momentum_25bp_60min",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_8h",
        sa.Column(
            "distance_to_nearest_cluster_below_pct",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_8h",
        sa.Column(
            "eth_iv_zscore_30d",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_8h",
        sa.Column(
            "cluster_strength_nearest_above_pct",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_8h",
        sa.Column(
            "distance_to_largest_cluster_above_pct",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_8h",
        sa.Column(
            "realized_volatility_60min",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_8h",
        sa.Column(
            "depth_imbalance_500bp",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_8h",
        sa.Column(
            "pressure_gradient_near",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_8h",
        sa.Column(
            "depth_imbalance_25bp",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_8h",
        sa.Column("trade_frequency", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "feature_store_8h",
        sa.Column(
            "vanna_exposure_zscore_24h",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_8h",
        sa.Column(
            "eth_put_call_ratio_1h_zscore_30d",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_8h",
        sa.Column(
            "options_orderbook_imbalance",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_8h",
        sa.Column(
            "avg_order_size_5bp_zscore_24h",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_8h",
        sa.Column(
            "imbalance_gradient_5bp_to_25bp",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_8h",
        sa.Column(
            "liquidity_concentration_5bp_vs_100bp",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_8h",
        sa.Column(
            "net_buy_pressure_absolute_zscore_24h",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_8h",
        sa.Column(
            "imbalance_momentum_5bp_15min",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_8h",
        sa.Column(
            "liquidity_stress_indicator_15m",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_8h",
        sa.Column(
            "net_gamma_density",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_8h",
        sa.Column(
            "distance_to_largest_cluster_below_pct",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_8h",
        sa.Column(
            "liquidity_adjusted_momentum_15m",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_8h",
        sa.Column(
            "pressure_gradient_far",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_8h",
        sa.Column(
            "depth_pressure_correlation_5bp_4h",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_8h",
        sa.Column(
            "iv_slope_4h",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_8h",
        sa.Column(
            "depth_imbalance_5bp",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_8h",
        sa.Column(
            "iv_slope",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_8h",
        sa.Column(
            "gamma_squeeze_potential_15m",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_8h",
        sa.Column(
            "market_microstructure_toxicity_15m",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_8h",
        sa.Column(
            "avg_order_size_100bp_zscore_24h",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_8h",
        sa.Column(
            "imbalance_consistency_score",
            sa.BOOLEAN(),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_8h",
        sa.Column(
            "liquidity_concentration_25bp_vs_500bp",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_8h",
        sa.Column(
            "iv_zscore_24h",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_8h",
        sa.Column(
            "pressure_gradient_divergence",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_8h",
        sa.Column(
            "trade_frequency_momentum_60min",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_8h",
        sa.Column(
            "volume_volatility_4h",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_8h",
        sa.Column(
            "volatility_risk_premium_15m",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_8h",
        sa.Column(
            "net_delta_exposure_zscore_24h",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_8h",
        sa.Column(
            "pressure_inversion_5bp_vs_500bp",
            sa.BOOLEAN(),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_8h",
        sa.Column(
            "effective_depth_5bp_zscore_24h",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_8h",
        sa.Column(
            "gamma_exposure_zscore_24h",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_8h",
        sa.Column(
            "pressure_concentration_near",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_8h",
        sa.Column(
            "order_flow_toxicity_15m",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_8h",
        sa.Column(
            "order_book_resilience_15m",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_8h",
        sa.Column(
            "options_flow_sentiment_15m",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_8h",
        sa.Column(
            "net_buy_pressure_ratio",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_8h",
        sa.Column(
            "btc_iv_zscore_30d",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_8h",
        sa.Column(
            "iv_trend_strength",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_8h",
        sa.Column(
            "price_volatility_4h",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_8h",
        sa.Column(
            "spread_percentile_rank_4h",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_8h",
        sa.Column(
            "cluster_strength_largest_above_pct",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_8h",
        sa.Column(
            "pressure_correlation_25bp_500bp_4h",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_8h",
        sa.Column(
            "effective_depth_100bp",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_8h",
        sa.Column(
            "pressure_momentum_25bp_15min",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_8h",
        sa.Column(
            "charm_exposure_zscore_24h",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_8h",
        sa.Column(
            "depth_momentum_5bp_15min",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_8h",
        sa.Column(
            "pressure_mean_reversion_5bp_4h",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_8h",
        sa.Column(
            "market_depth_imbalance_momentum_15m",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_8h",
        sa.Column(
            "volatility_surface_skew_15m",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_8h",
        sa.Column("iv_shock_evt", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "feature_store_8h",
        sa.Column(
            "imbalance_gradient_25bp_to_100bp",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_8h",
        sa.Column(
            "pressure_momentum_5bp_15min",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_8h",
        sa.Column(
            "net_buy_momentum_15min",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_8h",
        sa.Column(
            "pressure_inversion_strength",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_8h",
        sa.Column(
            "long_short_ratio_extreme_evt",
            sa.INTEGER(),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_8h",
        sa.Column(
            "btc_dvol_1d",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_8h",
        sa.Column(
            "cluster_strength_nearest_below_pct",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_8h",
        sa.Column(
            "cluster_strength_largest_below_pct",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_8h",
        sa.Column(
            "net_delta_exposure",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_8h",
        sa.Column(
            "eth_dvol_1d",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_8h",
        sa.Column(
            "long_short_ratio_zscore",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_8h",
        sa.Column(
            "avg_trade_size_usd_zscore_24h",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_8h",
        sa.Column(
            "net_gamma_exposure_zscore_24h",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_8h",
        sa.Column(
            "order_count_concentration_5bp",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_8h",
        sa.Column(
            "effective_depth_25bp_zscore_24h",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_8h",
        sa.Column(
            "market_maker_inventory_proxy_15m",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_8h",
        sa.Column(
            "buy_sell_trade_ratio",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_8h",
        sa.Column(
            "imbalance_gradient_100bp_to_500bp",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_8h",
        sa.Column(
            "liquidity_percentile_rank_4h",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_8h",
        sa.Column(
            "vanna_exposure",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_8h",
        sa.Column(
            "pressure_correlation_5bp_100bp_4h",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_4h",
        sa.Column(
            "entropy_based_uncertainty_15m",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_4h",
        sa.Column(
            "spread_volatility_4h",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_4h",
        sa.Column(
            "btc_put_call_ratio_zscore_30d",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_4h",
        sa.Column(
            "put_call_ratio_1h",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_4h",
        sa.Column(
            "pressure_gradient_medium",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_4h",
        sa.Column(
            "iv_pctile_30d",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_4h",
        sa.Column(
            "distance_to_nearest_cluster_above_pct",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_4h",
        sa.Column(
            "long_short_ratio_slope",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_4h",
        sa.Column(
            "liquidity_provision_cost_15m",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_4h",
        sa.Column(
            "buy_volume_dominance",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_4h",
        sa.Column(
            "pressure_momentum_5bp_60min",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_4h",
        sa.Column(
            "depth_imbalance_100bp",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_4h",
        sa.Column(
            "options_gamma_hedging_flow_15m",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_4h",
        sa.Column(
            "imbalance_momentum_25bp_60min",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_4h",
        sa.Column(
            "delta_gamm_inter",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_4h",
        sa.Column(
            "depth_momentum_25bp_60min",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_4h",
        sa.Column(
            "distance_to_nearest_cluster_below_pct",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_4h",
        sa.Column(
            "eth_iv_zscore_30d",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_4h",
        sa.Column(
            "cluster_strength_nearest_above_pct",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_4h",
        sa.Column(
            "distance_to_largest_cluster_above_pct",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_4h",
        sa.Column(
            "realized_volatility_60min",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_4h",
        sa.Column(
            "depth_imbalance_500bp",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_4h",
        sa.Column(
            "pressure_gradient_near",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_4h",
        sa.Column(
            "depth_imbalance_25bp",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_4h",
        sa.Column("trade_frequency", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "feature_store_4h",
        sa.Column(
            "vanna_exposure_zscore_24h",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_4h",
        sa.Column(
            "eth_put_call_ratio_1h_zscore_30d",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_4h",
        sa.Column(
            "options_orderbook_imbalance",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_4h",
        sa.Column(
            "avg_order_size_5bp_zscore_24h",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_4h",
        sa.Column(
            "imbalance_gradient_5bp_to_25bp",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_4h",
        sa.Column(
            "liquidity_concentration_5bp_vs_100bp",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_4h",
        sa.Column(
            "net_buy_pressure_absolute_zscore_24h",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_4h",
        sa.Column(
            "imbalance_momentum_5bp_15min",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_4h",
        sa.Column(
            "liquidity_stress_indicator_15m",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_4h",
        sa.Column(
            "net_gamma_density",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_4h",
        sa.Column(
            "distance_to_largest_cluster_below_pct",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_4h",
        sa.Column(
            "liquidity_adjusted_momentum_15m",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_4h",
        sa.Column(
            "pressure_gradient_far",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_4h",
        sa.Column(
            "depth_pressure_correlation_5bp_4h",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_4h",
        sa.Column(
            "iv_slope_4h",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_4h",
        sa.Column(
            "depth_imbalance_5bp",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_4h",
        sa.Column(
            "iv_slope",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_4h",
        sa.Column(
            "gamma_squeeze_potential_15m",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_4h",
        sa.Column(
            "market_microstructure_toxicity_15m",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_4h",
        sa.Column(
            "avg_order_size_100bp_zscore_24h",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_4h",
        sa.Column(
            "imbalance_consistency_score",
            sa.BOOLEAN(),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_4h",
        sa.Column(
            "liquidity_concentration_25bp_vs_500bp",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_4h",
        sa.Column(
            "iv_zscore_24h",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_4h",
        sa.Column(
            "pressure_gradient_divergence",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_4h",
        sa.Column(
            "trade_frequency_momentum_60min",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_4h",
        sa.Column(
            "volume_volatility_4h",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_4h",
        sa.Column(
            "volatility_risk_premium_15m",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_4h",
        sa.Column(
            "net_delta_exposure_zscore_24h",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_4h",
        sa.Column(
            "pressure_inversion_5bp_vs_500bp",
            sa.BOOLEAN(),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_4h",
        sa.Column(
            "effective_depth_5bp_zscore_24h",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_4h",
        sa.Column(
            "gamma_exposure_zscore_24h",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_4h",
        sa.Column(
            "pressure_concentration_near",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_4h",
        sa.Column(
            "order_flow_toxicity_15m",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_4h",
        sa.Column(
            "order_book_resilience_15m",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_4h",
        sa.Column(
            "options_flow_sentiment_15m",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_4h",
        sa.Column(
            "net_buy_pressure_ratio",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_4h",
        sa.Column(
            "btc_iv_zscore_30d",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_4h",
        sa.Column(
            "iv_trend_strength",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_4h",
        sa.Column(
            "price_volatility_4h",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_4h",
        sa.Column(
            "spread_percentile_rank_4h",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_4h",
        sa.Column(
            "cluster_strength_largest_above_pct",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_4h",
        sa.Column(
            "pressure_correlation_25bp_500bp_4h",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_4h",
        sa.Column(
            "effective_depth_100bp",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_4h",
        sa.Column(
            "pressure_momentum_25bp_15min",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_4h",
        sa.Column(
            "charm_exposure_zscore_24h",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_4h",
        sa.Column(
            "depth_momentum_5bp_15min",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_4h",
        sa.Column(
            "pressure_mean_reversion_5bp_4h",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_4h",
        sa.Column(
            "market_depth_imbalance_momentum_15m",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_4h",
        sa.Column(
            "volatility_surface_skew_15m",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_4h",
        sa.Column("iv_shock_evt", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "feature_store_4h",
        sa.Column(
            "imbalance_gradient_25bp_to_100bp",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_4h",
        sa.Column(
            "pressure_momentum_5bp_15min",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_4h",
        sa.Column(
            "net_buy_momentum_15min",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_4h",
        sa.Column(
            "pressure_inversion_strength",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_4h",
        sa.Column(
            "long_short_ratio_extreme_evt",
            sa.INTEGER(),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_4h",
        sa.Column(
            "btc_dvol_1d",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_4h",
        sa.Column(
            "cluster_strength_nearest_below_pct",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_4h",
        sa.Column(
            "cluster_strength_largest_below_pct",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_4h",
        sa.Column(
            "net_delta_exposure",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_4h",
        sa.Column(
            "eth_dvol_1d",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_4h",
        sa.Column(
            "long_short_ratio_zscore",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_4h",
        sa.Column(
            "avg_trade_size_usd_zscore_24h",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_4h",
        sa.Column(
            "net_gamma_exposure_zscore_24h",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_4h",
        sa.Column(
            "order_count_concentration_5bp",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_4h",
        sa.Column(
            "effective_depth_25bp_zscore_24h",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_4h",
        sa.Column(
            "market_maker_inventory_proxy_15m",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_4h",
        sa.Column(
            "buy_sell_trade_ratio",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_4h",
        sa.Column(
            "imbalance_gradient_100bp_to_500bp",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_4h",
        sa.Column(
            "liquidity_percentile_rank_4h",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_4h",
        sa.Column(
            "vanna_exposure",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_4h",
        sa.Column(
            "pressure_correlation_5bp_100bp_4h",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_1h",
        sa.Column(
            "entropy_based_uncertainty_15m",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_1h",
        sa.Column(
            "spread_volatility_4h",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_1h",
        sa.Column(
            "btc_put_call_ratio_zscore_30d",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_1h",
        sa.Column(
            "put_call_ratio_1h",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_1h",
        sa.Column(
            "pressure_gradient_medium",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_1h",
        sa.Column(
            "iv_pctile_30d",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_1h",
        sa.Column(
            "distance_to_nearest_cluster_above_pct",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_1h",
        sa.Column(
            "long_short_ratio_slope",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_1h",
        sa.Column(
            "liquidity_provision_cost_15m",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_1h",
        sa.Column(
            "buy_volume_dominance",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_1h",
        sa.Column(
            "pressure_momentum_5bp_60min",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_1h",
        sa.Column(
            "depth_imbalance_100bp",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_1h",
        sa.Column(
            "options_gamma_hedging_flow_15m",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_1h",
        sa.Column(
            "imbalance_momentum_25bp_60min",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_1h",
        sa.Column(
            "delta_gamm_inter",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_1h",
        sa.Column(
            "depth_momentum_25bp_60min",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_1h",
        sa.Column(
            "distance_to_nearest_cluster_below_pct",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_1h",
        sa.Column(
            "eth_iv_zscore_30d",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_1h",
        sa.Column(
            "cluster_strength_nearest_above_pct",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_1h",
        sa.Column(
            "distance_to_largest_cluster_above_pct",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_1h",
        sa.Column(
            "realized_volatility_60min",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_1h",
        sa.Column(
            "depth_imbalance_500bp",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_1h",
        sa.Column(
            "pressure_gradient_near",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_1h",
        sa.Column(
            "depth_imbalance_25bp",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_1h",
        sa.Column("trade_frequency", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "feature_store_1h",
        sa.Column(
            "vanna_exposure_zscore_24h",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_1h",
        sa.Column(
            "eth_put_call_ratio_1h_zscore_30d",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_1h",
        sa.Column(
            "options_orderbook_imbalance",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_1h",
        sa.Column(
            "avg_order_size_5bp_zscore_24h",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_1h",
        sa.Column(
            "imbalance_gradient_5bp_to_25bp",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_1h",
        sa.Column(
            "liquidity_concentration_5bp_vs_100bp",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_1h",
        sa.Column(
            "net_buy_pressure_absolute_zscore_24h",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_1h",
        sa.Column(
            "imbalance_momentum_5bp_15min",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_1h",
        sa.Column(
            "liquidity_stress_indicator_15m",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_1h",
        sa.Column(
            "net_gamma_density",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_1h",
        sa.Column(
            "distance_to_largest_cluster_below_pct",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_1h",
        sa.Column(
            "liquidity_adjusted_momentum_15m",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_1h",
        sa.Column(
            "pressure_gradient_far",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_1h",
        sa.Column(
            "depth_pressure_correlation_5bp_4h",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_1h",
        sa.Column(
            "iv_slope_4h",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_1h",
        sa.Column(
            "depth_imbalance_5bp",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_1h",
        sa.Column(
            "iv_slope",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_1h",
        sa.Column(
            "gamma_squeeze_potential_15m",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_1h",
        sa.Column(
            "market_microstructure_toxicity_15m",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_1h",
        sa.Column(
            "avg_order_size_100bp_zscore_24h",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_1h",
        sa.Column(
            "imbalance_consistency_score",
            sa.BOOLEAN(),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_1h",
        sa.Column(
            "liquidity_concentration_25bp_vs_500bp",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_1h",
        sa.Column(
            "iv_zscore_24h",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_1h",
        sa.Column(
            "pressure_gradient_divergence",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_1h",
        sa.Column(
            "trade_frequency_momentum_60min",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_1h",
        sa.Column(
            "volume_volatility_4h",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_1h",
        sa.Column(
            "volatility_risk_premium_15m",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_1h",
        sa.Column(
            "net_delta_exposure_zscore_24h",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_1h",
        sa.Column(
            "pressure_inversion_5bp_vs_500bp",
            sa.BOOLEAN(),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_1h",
        sa.Column(
            "effective_depth_5bp_zscore_24h",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_1h",
        sa.Column(
            "gamma_exposure_zscore_24h",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_1h",
        sa.Column(
            "pressure_concentration_near",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_1h",
        sa.Column(
            "order_flow_toxicity_15m",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_1h",
        sa.Column(
            "order_book_resilience_15m",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_1h",
        sa.Column(
            "options_flow_sentiment_15m",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_1h",
        sa.Column(
            "net_buy_pressure_ratio",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_1h",
        sa.Column(
            "btc_iv_zscore_30d",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_1h",
        sa.Column(
            "iv_trend_strength",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_1h",
        sa.Column(
            "price_volatility_4h",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_1h",
        sa.Column(
            "spread_percentile_rank_4h",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_1h",
        sa.Column(
            "cluster_strength_largest_above_pct",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_1h",
        sa.Column(
            "pressure_correlation_25bp_500bp_4h",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_1h",
        sa.Column(
            "effective_depth_100bp",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_1h",
        sa.Column(
            "pressure_momentum_25bp_15min",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_1h",
        sa.Column(
            "charm_exposure_zscore_24h",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_1h",
        sa.Column(
            "depth_momentum_5bp_15min",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_1h",
        sa.Column(
            "pressure_mean_reversion_5bp_4h",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_1h",
        sa.Column(
            "market_depth_imbalance_momentum_15m",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_1h",
        sa.Column(
            "volatility_surface_skew_15m",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_1h",
        sa.Column("iv_shock_evt", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "feature_store_1h",
        sa.Column(
            "imbalance_gradient_25bp_to_100bp",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_1h",
        sa.Column(
            "pressure_momentum_5bp_15min",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_1h",
        sa.Column(
            "net_buy_momentum_15min",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_1h",
        sa.Column(
            "pressure_inversion_strength",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_1h",
        sa.Column(
            "long_short_ratio_extreme_evt",
            sa.INTEGER(),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_1h",
        sa.Column(
            "btc_dvol_1d",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_1h",
        sa.Column(
            "cluster_strength_nearest_below_pct",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_1h",
        sa.Column(
            "cluster_strength_largest_below_pct",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_1h",
        sa.Column(
            "net_delta_exposure",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_1h",
        sa.Column(
            "eth_dvol_1d",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_1h",
        sa.Column(
            "long_short_ratio_zscore",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_1h",
        sa.Column(
            "avg_trade_size_usd_zscore_24h",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_1h",
        sa.Column(
            "net_gamma_exposure_zscore_24h",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_1h",
        sa.Column(
            "order_count_concentration_5bp",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_1h",
        sa.Column(
            "effective_depth_25bp_zscore_24h",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_1h",
        sa.Column(
            "market_maker_inventory_proxy_15m",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_1h",
        sa.Column(
            "buy_sell_trade_ratio",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_1h",
        sa.Column(
            "imbalance_gradient_100bp_to_500bp",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_1h",
        sa.Column(
            "liquidity_percentile_rank_4h",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_1h",
        sa.Column(
            "vanna_exposure",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "feature_store_1h",
        sa.Column(
            "pressure_correlation_5bp_100bp_4h",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.create_table(
        "raw_ohlcv",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("timestamp", sa.BIGINT(), autoincrement=False, nullable=False),
        sa.Column("token", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("interval", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "open",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "high",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "low",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "close",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "volume",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("raw_ohlcv_pkey")),
    )
    op.create_index(op.f("ix_raw_ohlcv_token"), "raw_ohlcv", ["token"], unique=False)
    op.create_index(
        op.f("ix_raw_ohlcv_timestamp"), "raw_ohlcv", ["timestamp"], unique=False
    )
    op.drop_table("raw_ohlcv_4h")
    op.drop_table("raw_ohlcv_1h")
    op.drop_table("raw_ohlcv_1d")
    op.drop_table("raw_ohlcv_15m")
    # ### end Alembic commands ###
